###
GET http://localhost:3000/api/v1/books HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/v1/books/1111 HTTP/1.1
content-type: application/json


###
# /api/v1/books/:genre(/:status)(.:format)
GET http://localhost:3000/api/v1/books/genre/Horror/2 HTTP/1.1
content-type: application/json

###
# /api/v1/books/:genre(/:status)(.:format)
GET http://localhost:3000/api/v1/books/genre/Action/1&renew_cache=true HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/api/v1/books HTTP/1.1
content-type: application/json

{ 
    "book": {
        "title": "Marata",
        "author_id": 1,
        "publication_date": 2021,
        "genre": "Horror"
    }
}

###
POST http://localhost:3000/api/v1/books HTTP/1.1
content-type: application/json

{ 
    "book": {
        "title": "Marata",
        "author_id": 1,
        "publication_date": 2021,
        "genre": "Horror"
    }
}

###
PUT http://localhost:3000/api/v1/books/7 HTTP/1.1
content-type: application/json

{ 
    "book": {
        "title": "Bingo O filme",
        "author_id": 2,
        "publication_date": 2022,
        "genre": "Action"
    }
}

###
PUT http://localhost:3000/api/v1/books/8 HTTP/1.1
content-type: application/json

{ 
    "book": {
        "title": "Batata O filme",
        "author_id": 2,
        "publication_date": 2024,
        "genre": "Action"
    }
}



###
DELETE http://localhost:3000/api/v1/books/13 HTTP/1.1
content-type: application/json
