
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      #- db:/root/db
      - ./db/:/root/db/
    stdin_open: true
    tty: true

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/myapp
    tmpfs: /app/tmp
    depends_on:
      - db
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

  # webserver:
  #   tty: true
  #   stdin_open: true
  #   build: .
  #   command: ./run
  #   ports:
  #     - "3001:3000"
  #   links:
  #     - webpack
  #   environment:
  #     - RAILS_ENV=development

  # webpack:
  #   build: .
  #   command: bin/webpack-dev-server
  #   ports:
  #     - "8080:8080"
  #     - "35729:35729"
  #   environment:
  #     - NODE_ENV=development