###
GET http://localhost:3000/api/v1/books HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/v1/books/12 HTTP/1.1
content-type: application/json


###
# /api/v1/books/:genre(/:status)(.:format)
GET http://localhost:3000/api/v1/books/genre/Horror/2 HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/api/v1/books HTTP/1.1
content-type: application/json

{ 
    "book": {
        "title": "Genexus",
        "author_id": 4,
        "publication_date": "2021-01-31",
        "genre": "Horror"
    }
}

###
PUT http://localhost:3000/api/v1/books/17 HTTP/1.1
content-type: application/json

{ 
    "book": {
        "title": "Wolverine O filme",
        "author_id": 1,
        "publication_date": 2024,
        "genre": "Action"
    }
}

###
DELETE http://localhost:3000/api/v1/books/13 HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/v1/authors HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/api/v1/authors HTTP/1.1
content-type: application/json

{ 
    "author": {
        "title": "Mnango2",
        "author_id": 1,
        "publication_date": "2021-01-31",
        "genre": "Horror"
    }
}



